version: '2'
services:
  mymongdbapp-app:
    image: mymongdbapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mymongdbapp-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=mymongdbapp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  mymongdbapp-mongodb:
    extends:
      file: mongodb.yml
      service: mymongdbapp-mongodb
